nodeLinker: node-modules

packageExtensions:
  "@ng-doc/app@*":
    dependencies:
      "@ng-web-apis/common": "*"
      di-controls: "*"
  "@ng-doc/ui-kit@*":
    dependencies:
      "@ngneat/until-destroy": "*"
      "@tinkoff/ng-polymorpheus": 4.0.11
      di-controls: "*"
