name: demo app

on:
  push:
    branches: ["master"]

jobs:
  build:
    runs-on: ubuntu-latest
    # We only want to build and deploy the dev-app if the `dev-app preview` label has been
    # added, or if the label is already applied and new changes have been made in the PR.
    if: contains(github.event.pull_request.labels.*.name, 'demo-app')
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "16"
      - name: Install dependencies
        run: yarn install --frozen-lockfile
      - name: Build the project
        run: yarn build
      - name: Archive Production Artifact
        uses: actions/upload-artifact@v3
        with:
          name: dist
          path: dist/demo-app
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
      - name: Download Artifact
        uses: actions/download-artifact@v3
        with:
          name: dist
          path: dist/demo-app
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: dist/demo-app
          enable_jekyll: true
