name: ngx-mat-timepicker publish v16

on:
  release:
    types: [published]
    branches: ["16.x.x"]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20.9.x]

    steps:
      - uses: actions/checkout@v3
        with:
          ref: 16.x.x
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "yarn"
      - name: Install dependencies
        run: yarn install --frozen-lockfile
      - name: Build
        run: yarn run build:lib
      - name: Publish on npm
        uses: JS-DevTools/npm-publish@v3
        with:
          token: ${{ secrets.NPM_TOKEN }}
          package: dist/mat-timepicker
          tag: latest-v16
